//task1
const divEl = document.getElementById('divToEdit');
const textAreaEl = document.getElementById('textAreaToEdit');

window.addEventListener('keydown', function (event) {
    if (event.ctrlKey == true && event.code == "KeyE") {
        event.preventDefault();

        textAreaEl.classList.add("edit__block--visible");
        divEl.classList.remove("edit__block--visible");
        divEl.classList.add("edit__block--hidden");

        textAreaEl.value = divEl.innerText;
        textAreaEl.focus();
    }
});

// for text - '+' is generated by Shift + '=', so need to press Ctrl + Shift + '='
window.addEventListener('keydown', function (event) {
    if (event.ctrlKey == true && event.key == '+') {
        event.preventDefault();

        divEl.classList.add("edit__block--visible");
        textAreaEl.classList.remove("edit__block--visible");
        textAreaEl.classList.add("edit__block--hidden");

        divEl.innerText = textAreaEl.value;
    }
});

//task2
function sortTable(idx) {
    let table, rows, switching, i, x, y, shouldSwitch;
    table = document.getElementById("tablepress");
    switching = true;
    while (switching) {
        switching = false;
        rows = table.rows;
        for (i = 1; i < (rows.length - 1); i++) {
            shouldSwitch = false;
            x = rows[i].getElementsByTagName("td")[idx];
            y = rows[i + 1].getElementsByTagName("td")[idx];
            if (!Number.isNaN(Number(x.innerHTML))) {
                if (Number(x.innerHTML) > Number(y.innerHTML)) {
                    shouldSwitch = true;
                    break;
                }
            } else if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                shouldSwitch = true;
                break;
            }
        }
        if (shouldSwitch) {
            rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
            switching = true;
        }
    }
}

let tblHeaders = document.getElementsByClassName('tablepress_header');
for (let i = 0; i < tblHeaders.length; i++) {
    tblHeaders[i].addEventListener("click", function () { sortTable(i) }, false);
}